Add language server 2201.2.2 release note
ballerina-platform/ballerina-release pull request #2159
Opened 2022-10-21 04:42 UTC by gayalkuruppu

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.

## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2022-10-21 05:26 UTC, IMS94 requested changes

2022-10-21 05:26 UTC, IMS94 commented on release-notes/swan-lake-release-notes/swan-lake-2201.2.2-release-note.md
> +- Introduced new API to load a project into the Workspace Manager
@gayalkuruppu we added following new features as well:
1. Extract to function
2. Extract to local variable
3. Rename popup for create variable code action <- Let's add this under a new feature

2022-10-21 05:26 UTC, IMS94 commented on test-scripts/ballerina-test-automation/.settings/org.eclipse.buildship.core.prefs
> +arguments=--init-script /var/folders/sb/7j7ln5gn72g1sc15bm9l2vgm0000gn/T/init15326630906069179233.gradle --init-script /var/folders/sb/7j7ln5gn72g1sc15bm9l2vgm0000gn/T/init10568042303374396679.gradle
@gayalkuruppu these are non-related changes right?

2022-10-21 05:59 UTC, gayalkuruppu commented on test-scripts/ballerina-test-automation/.settings/org.eclipse.buildship.core.prefs
> +arguments=--init-script /var/folders/sb/7j7ln5gn72g1sc15bm9l2vgm0000gn/T/init15326630906069179233.gradle --init-script /var/folders/sb/7j7ln5gn72g1sc15bm9l2vgm0000gn/T/init10568042303374396679.gradle
Yeah will remove them

2022-10-21 09:10 UTC, mohanvive approved these changes

2022-10-23 01:49 UTC, praneesha commented
@gayalkuruppu - Please send these updates to https://github.com/ballerina-platform/ballerina-dev-website/tree/dev/downloads/swan-lake-release-notes/swan-lake-2201.2.2 as the release note is already live now.

2022-10-25 04:14 UTC, IMS94 commented
Sent in https://github.com/ballerina-platform/ballerina-dev-website/pull/5685. Hence closing

2022-10-25 04:14 UTC, closed without merging